### ISSUE TITLE
Have you removed tags?

### ISSUE THREAD

**Issue by camspiers** [Nyholm/google-api-php-client#1]
If so, please don't do this in future. We have released libraries that depend on tags that I believe you previously released. This is very frustrating as now our library is not installable via composer.

**Comment by Nyholm** [comment]
No of course not.. But I am surprised that there is not tags ATM. But I have not changed this library since I heard that the improved the [official repo](https://github.com/google/google-api-php-client). And that's about a year ago.

**Comment by camspiers** [comment]
Oh okay, sorry about the accusation. Where did the tags go then? From what I can tell there used to be tags...
