### ISSUE TITLE
Google_Client Does Not Exist?

### ISSUE THREAD

**Issue by javalight** [Nyholm/google-api-php-client#2]
Im abit confused with this package. The example code does not match the classes in the repository. I cant fined Google_Client instead i have been using the Client Class.

**Comment by Nyholm** [comment]
Have a look at the latest version of the package. It is hosted in this repo: https://github.com/google/google-api-php-client

**Comment by javalight** [comment]
Ah yes i see now thanks! Is there a packagist version of this repo? Im using laravel.

**Comment by Nyholm** [comment]
Sure. Look in the [composer.json file](https://github.com/google/google-api-php-client/blob/master/composer.json#L2)
